Update logs_cleanup.yml

diff --git a/.github/workflows/logs_cleanup.yml b/.github/workflows/logs_cleanup.yml
--- a/.github/workflows/logs_cleanup.yml
+++ b/.github/workflows/logs_cleanup.yml
@@ -44,11 +44,15 @@ jobs:
           sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no user1@192.168.1.105 <<EOF
           cd /home/user1/Practice
           job=$(find . -type f -name "delete_logs.sh" | head -n 1)
-          echo "Exececuting chmod command"
-          chmod +x "$job"
-          echo $?
-          echo "Executing the bash script now"
-          bash "$job"            
-          echo "Status of bash script execution is"
-          echo $?     
+          if [ -n "$job" ]; then
+            echo "Executing chmod command"
+            chmod +x "$job"
+            echo "chmod exit status: $?"
+            echo "Executing the bash script now"
+            bash "$job"
+            echo "Script execution status: $?"
+          else
+            echo "delete_logs.sh not found"
+            exit 1
+          fi
           EOF
